/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/sync-linkedin-profile.mjs
 * Do not edit by hand - update content/linkedin/profile.json and run:
 *   npm run sync:linkedin
 *
 * Source: Manual LinkedIn profile snapshot - https://www.linkedin.com/in/iftekhareather/
 * Updated: 2026-09-13
 */
export const linkedInGenerated = {
  "updatedAt": "2026-09-13",
  "source": "Manual LinkedIn profile snapshot - https://www.linkedin.com/in/iftekhareather/",
  "siteConfig": {
    "title": "Technical Lead · Senior System Engineer · System Architecture · Cloud (AWS & Alibaba Cloud)",
    "tagline": "Engineering Manager · System Architecture · Cloud (AWS & Alibaba Cloud)",
    "summary": "Technical Lead and Senior System Engineer with 16+ years delivering enterprise software, SaaS platforms, AI solutions, and government digital transformation projects across Japan and Bangladesh. Seven-plus years leading Agile/Scrum teams through full delivery lifecycles: architecture, cloud infrastructure, backend engineering, and stakeholder alignment. Certified Scrum Alliance professional (CSPO, CSM, A-CSD, CSD).",
    "location": "Saitama, Japan"
  },
  "focusAreas": [
    "Technical Lead",
    "Senior System Engineer",
    "System Architecture",
    "AWS",
    "Alibaba Cloud",
    "Backend & Full-Stack",
    "AI & SaaS"
  ],
  "stats": [
    {
      "label": "Years Experience",
      "value": "16+"
    },
    {
      "label": "Teams Led",
      "value": "10+"
    },
    {
      "label": "Certifications",
      "value": "4"
    },
    {
      "label": "Projects Delivered",
      "value": "20+"
    }
  ],
  "skills": [
    {
      "category": "Leadership & Delivery",
      "items": [
        "Technical Lead",
        "Engineering Management",
        "Agile / Scrum",
        "Stakeholder Management",
        "Roadmap & Release Strategy",
        "Cross-functional Teams"
      ]
    },
    {
      "category": "System Architecture & Cloud",
      "items": [
        "System Architecture",
        "AWS",
        "Alibaba Cloud (Aliyun)",
        "Site Reliability Engineering",
        "Linux",
        "CI/CD",
        "Infrastructure Design",
        "Terraform"
      ]
    },
    {
      "category": "Backend & Full-Stack",
      "items": [
        "Laravel",
        "PHP",
        "Python",
        "FastAPI",
        "Node.js",
        "MySQL",
        "Vue.js",
        "WordPress"
      ]
    },
    {
      "category": "AI & SaaS",
      "items": [
        "RAG Architecture",
        "Vector Databases",
        "Agentic AI",
        "SaaS / Multi-tenant",
        "Docker",
        "WebSockets",
        "OCR Workflows"
      ]
    }
  ],
  "recommendations": [
    {
      "name": "Mizanur Rahman",
      "title": "Colleague",
      "quote": "Iftekhar is a fast learner and a genuinely hardworking professional. His attention to detail, curiosity, and appetite to learn consistently impressed me. A certified Agile and Scrum professional, Iftekhar communicates with real clarity and has proven himself a dependable team player. He would be a valuable addition to any engineering team, and I recommend him without hesitation.",
      "linkedin": "https://www.linkedin.com/in/mizan"
    },
    {
      "name": "Mohammad Hasan Tareq",
      "title": "Former Colleague",
      "quote": "Beyond his strong skills in system engineering, cloud solutions, and project management, Iftekhar was always ready to step up and help anyone facing a challenge. I strongly recommend Iftekhar to any organization looking for an outstanding leader and system architect.",
      "linkedin": "https://www.linkedin.com/in/hsntareq"
    }
  ]
} as {
  updatedAt: string;
  source: string;
  siteConfig: {
    title: string;
    tagline: string;
    summary: string;
    location: string;
  };
  focusAreas: string[];
  stats: { label: string; value: string }[];
  skills: { category: string; items: string[] }[];
  recommendations: {
    name: string;
    title: string;
    quote: string;
    linkedin: string;
  }[];
};

export type LinkedInGenerated = typeof linkedInGenerated;
